### ISSUE TITLE
Choose network framework

### ISSUE THREAD

**Issue by t3hk0d3** [tainz/Glydar-Old#1]
Managing client sockets/threads on your own is not quite good idea.

Netty? http://netty.io/

> Netty is an asynchronous event-driven network application framework 
> for rapid development of maintainable high performance protocol servers & clients.

Vanilla minecraft server is so crappy because of thread (well actually several threads) per user model.

Event based model + few threads for game logic (physics/etc) should be much better.

**Comment by PsychoNineSix** [comment]
We've considered Netty, but we've chosen to manage them on our own. And our networking programmer is quite experienced at networking.

**Comment by t3hk0d3** [comment]
What pros on writing own networking solution?
Hope i shouldn't tell you cons of that approach?

**Comment by Mitch528** [comment]
Switch to Netty completed.
